version: "2.4"

services:
  mysql-vision-web:
    image: mysql:8.0
    container_name: mysql-vision-web-2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vision_web_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s  
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - visionnet

  backend:
    build:
      context: ./api-vision-web/api--vision-web
      dockerfile: Dockerfile
    container_name: vision-web-backend
    depends_on:
      mysql-vision-web:
          condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-vision-web:3306/vision_web_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    restart: on-failure  
    networks:
      - visionnet

  frontend:
    build:
      context: ./app-vision-web
      dockerfile: Dockerfile
    container_name: vision-web-frontend
    depends_on:
      - backend
    environment:
      # exemplo: se o front precisar de URL da API
      VITE_API_URL: http://backend:8080
    ports:
      - "5173:5173"
    networks:
      - visionnet

networks:
  visionnet:
    driver: bridge
